export interface CategoryGroup {
  title: string;
  categories: string[];
}

export const categoryGroups: CategoryGroup[] = [
  {
    title: "Era-Style",
    categories: [
      "Pyramid Eras",
      "Egyptian",
      "Sumerian",
      "Mesopotamian",
      "Aztec",
      "Ancient Whodanian (China Ancient)",
      "Ancient Pagan African",
      "Ancient Pagan Black Australian",
      "Ancient Pagan Indian",
      "Easter Island",
      "Ancient Island Cultures",
      "Ancient Pagan Arabian",
      "Ancient Pagan Japan",
      "Temple Cultures",
      "Greece",
      "Roman",
      "Japan",
      "China",
      "India",
      "Church Cultures",
      "Byzantian",
      "Roman Medieval",
      "Gothic Medieval",
      "Slavic Medieval",
      "Northern Europe Medieval",
      "Arabian Medieval",
      "First Enlightenment",
      "Renaissance",
      "Mannerism",
      "Baroque",
      "Rococo",
      "Second Enlightenment",
      "Neoclassicism",
      "Romanticism",
      "Symbolism",
      "Decadentism",
      "Empire",
      "Beidermeier",
      "Academics",
      "Decorative",
      "Arte Povera",
      "Artisan Conceptual",
      "Decorative Conceptual",
      "Kitsch Conceptual",
      "Solipsist Conceptual",
      "Technical Marvel Conceptual",
      "Late Modern Expressionism",
      "Modernism and Postmodernism Underground",
      "Impressionism",
      "Expressionism",
      "Fauvism",
      "Pointillism",
      "Dadaism",
      "Surrealism",
      "Conceptualism",
      "Abstraction",
      "NeoGothic Advent",
      "Futurism",
      "Haute Baroque",
      "Haute Rococo",
      "Haute Neoclassicism",
      "Islamic Golden Age",
      "Horror",
      "Post Modernism Underground",
      "Haute Minimalism",
      "Haute Symbolism",
      "Haute Romanticism (Black Metal)",
      "Martial Industrial",
      "Haute Surrealism",
      "Arch Baroque",
      "Arch Rococo",
      "Arch Neoclassicism",
      "Arch Horror",
      "Afrofuturism",
      "ASCII Art",
      "Abstract Art",
      "Art Brut",
      "Abstract Expressionism",
      "Abstract Illusionism",
      "Academic Art",
      "Aestheticism",
      "Altermodern",
      "American Barbizon School",
      "American Impressionism",
      "American Realism",
      "American Scene Painting",
      "Analytical Art",
      "Antipodeans",
      "Arabesque",
      "Arbeitsrat für Kunst",
      "Art & Language",
      "Art Deco",
      "Art Informel",
      "Art Nouveau",
      "Art Photography",
      "Artificial Intelligence Art",
      "Arts and Crafts Movement",
      "Ashcan School",
      "Assemblage",
      "Australian Tonalism",
      "Les Automatistes",
      "Auto-destructive Art",
      "Avant-garde",
      "Barbizon School",
      "Bauhaus",
      "Berlin Secession",
      "Black Arts Movement",
      "Bengal School of Art",
      "Brutalism",
      "Classical Realism",
      "Cloisonnism",
      "COBRA",
      "Color Field",
      "Context Art",
      "Computer Art",
      "Concrete Art",
      "Conceptual Art",
      "Constructivism",
      "Crystal Cubism",
      "Cubo-Futurism",
      "Cubism",
      "Cynical Realism",
      "Dada",
      "Dansaekhwa",
      "Danube School",
      "Dau-al-Set",
      "De Stijl",
      "Deconstructivism",
      "Didacticism",
      "Digital Art",
      "Ecological Art",
      "Environmental Art",
      "Modern European Ink Painting",
      "Excessivism",
      "Exoticism",
      "Fantastic Realism",
      "Fauvism",
      "Feminist Art",
      "Figurative Art",
      "Figuration Libre",
      "Fine Art",
      "Folk Art",
      "Flemish Painting",
      "Fluxus",
      "Funk Art",
      "Geometric Abstract Art",
      "Glitch Art",
      "Graffiti/Street Art",
      "Gutai Group",
      "Gothic Art",
      "Happening",
      "Harlem Renaissance",
      "Heidelberg School",
      "Hudson River School",
      "Hurufiyya",
      "Hypermodernism",
      "Hyperrealism",
      "Illustrative",
      "Interactive Art",
      "Institutional Critique",
      "International Gothic",
      "International Typographic Style",
      "Japonisme",
      "Kinetic Art",
      "Kitsch Movement",
      "Land Art",
      "Les Nabis",
      "Letterism",
      "Light and Space",
      "Lowbrow",
      "Lyco Art",
      "Lyrical Abstraction",
      "Magic Realism",
      "Mail Art",
      "Mannerism",
      "Massurrealism",
      "Maximalism",
      "Metaphysical Painting",
      "Mingei",
      "Minimalism",
      "Modernism",
      "Modular Constructivism",
      "Naive Art",
      "Neo-Dada",
      "Neo-expressionism",
      "Neo-Fauvism",
      "Neo-figurative",
      "Neo-primitivism",
      "Neo-romanticism",
      "Net Art",
      "New Objectivity",
      "New Sculpture",
      "Northwest School",
      "Nuclear Art",
      "Objective Abstraction",
      "Op Art",
      "Orphism",
      "Patna School of Painting",
      "Photorealism",
      "Panfuturism",
      "Paris School",
      "Pixel Art",
      "Plasticien",
      "Plein Air",
      "Pop Art",
      "Post-impressionism",
      "Postminimalism",
      "Precisionism",
      "Primitivism",
      "Private Press",
      "Process Art",
      "Psychedelic Art",
      "Purism",
      "Rayonism",
      "Realism",
      "Regionalism",
      "Remodernism",
      "Retrofuturism",
      "Romanesque",
      "Samikshavad",
      "Serial Art",
      "Shin Hanga",
      "Shock Art",
      "Sōsaku Hanga",
      "Socialist Realism",
      "Sots Art",
      "Space Art",
      "Street Art",
      "Stuckism",
      "Sumatraism",
      "Superflat",
      "Suprematism",
      "Synchromism",
      "Synthetism",
      "Tachisme",
      "Temporary Art",
      "Toyism",
      "Transgressive Art",
      "Tonalism",
      "Ukiyo-e",
      "Underground Comix",
      "Vancouver School",
      "Vanitas",
      "Verdadism",
      "Video Art",
      "Visual Art",
      "Viennese Actionism",
      "Vorticism",
      "Steampunk",
      "Primitive",
      "21st Century Avant-Garde",
      "NeoClassic",
      "NeoPagan",
      "Fantasy",
      "Industrial Deco"
    ]
  },
  {
    title: "Medium",
    categories: [
      "Lesbian Kisses Rococo",
      "Lesbian Kisses Baroque",
      "Lesbian Kisses Mannerism",
      "Lesbian Kisses Renaissance",
      "Lesbian Kisses Medieval Gothic",
      "Lesbian Kisses Medieval Roman",
      "Lesbian Kisses Roman",
      "Lesbian Kisses Greek",
      "Lesbian Kisses Mesopotamian",
      "Lesbian Kisses Egyptian",
      "Lesbian Kisses Indian",
      "Lesbian Kisses Far Orient",
      "Islamic Lesbian Kisses",
      "African Lesbian Kisses",
      "Lesbian Kisses Mix",
      "Blonde on Brunette",
      "Blonde on Blonde",
      "Brunette on Brunette",
      "Redheads Succubi Kisses",
      "Purple Hair",
      "Bleu Hair",
      "Emo Lesbian Kisses",
      "Vampire Lesbian Kisses",
      "Angel Lesbian Kisses",
      "Shieldmaidens Lesbian Kisses",
      "Emo Page Lesbian Kisses",
      "Search Incomplete (sketches, paint documents, amateur designing)",
      "Search Semicomplete (talented ideas, thorough paint projects, advanced design)",
      "Search Majesty (academic, fully composed, impeccable design)",
      "Seazon: Winter",
      "Seazon: Spring",
      "Seazon: Summer",
      "Seazon: Autumn",
      "Craft Medium: Oil Painting",
      "Craft Medium: Acrylic Painting",
      "Craft Medium: Aquarell",
      "Craft Medium: Engraving",
      "Craft Medium: Lithography",
      "Craft Medium: Monochrome",
      "Craft Medium: Monocolor",
      "Craft Medium: Collage",
      "Craft Medium: Relief",
      "Craft Medium: Bass Relief",
      "Craft Medium: Crayon",
      "Craft Medium: Pastel",
      "Craft Medium: Sketch",
      "Craft Medium: Virtual 2D",
      "Craft Medium: Virtual 3D",
      "Craft Medium: AI",
      "Artistic Color: Kitsch",
      "Artistic Color: Classic Decorative",
      "Artistic Color: Academic Sublime Decorative",
      "Artistic Color: Impressionistic",
      "Artistic Color: Expressionistic",
      "Artistic Color: Abstract Idealist",
      "Artistic Color: High Kitsch",
      "Artistic Color: Pastiche of Styles",
      "Metal Covers: Metal",
      "Metal Covers: Oldschool",
      "Metal Covers: Satanic",
      "Metal Covers: Trve Nature",
      "Metal Covers: Trve Experimental (Classic Victorian)",
      "Metal Covers: Trve Modern (Modern Features)",
      "Concept: Minimal",
      "Concept: Solipsistic",
      "Concept: Abstract Defaitist",
      "Concept: Installation",
      "Concept: Performance",
      "Concept: Post Deco Formal",
      "Concept: Conceptual Decorative",
      "Concept: Conceptual Allegoric",
      "Concept: Conceptual Technology",
      "Concept: Steampunk Styled",
      "Color: Black and White",
      "Color: Sepia",
      "Color: Red",
      "Color: Bleu",
      "Color: Yellow",
      "Color: Purple",
      "Color: Green",
      "Color: Orange",
      "Color: Technicolor",
      "Color: Hand Colored",
      "Color: Digital Color",
      "Theme: Historical Landscape",
      "Theme: Bridge",
      "Theme: Building",
      "Theme: Village",
      "Theme: Meadows",
      "Theme: Forest",
      "Theme: Still Life",
      "Theme: Life",
      "Theme: Technology",
      "Theme: Steam Era",
      "Theme: Television and Radio Era",
      "Modern Time Scenery: Post WWII",
      "Modern Time Scenery: Hippie Era",
      "Modern Time Scenery: 70s",
      "Modern Time Scenery: Early Synthpop",
      "Modern Time Scenery: Early New Wave Scene",
      "Modern Time Scenery: 80s",
      "Modern Time Scenery: Early Metal Scene",
      "Modern Time Scenery: 90s",
      "Modern Time Scenery: Early Black Metal Scene",
      "Modern Time Scenery: Internet Era Matrix",
      "Style of Life Depicted: Gluttony",
      "Style of Life Depicted: Enormous Wealth",
      "Style of Life Depicted: Decadence",
      "Style of Life Depicted: Monarchy",
      "Style of Life Depicted: Religious Life",
      "Style of Life Depicted: Civil Life",
      "Style of Life Depicted: Narrow Mindedness",
      "Style of Life Depicted: Labour",
      "Style of Life Depicted: Poverty",
      "Style of Life Depicted: Malnutrition",
      "Style of Life Depicted: Death",
      "Style of Life Depicted: Technology",
      "Style of Life Depicted: Fantasy",
      "Classical Topic and Themes: Mythology",
      "Classical Topic and Themes: Allegory",
      "Classical Topic and Themes: Portraits",
      "Classical Topic and Themes: Full Figure",
      "Classical Topic and Themes: Group",
      "Classical Topic and Themes: Classic Nude",
      "Classical Topic and Themes: Group Scene Classic Nude",
      "Classical Topic and Themes: Landscape Mountains / Meadows",
      "Classical Topic and Themes: Fantastic Landscape",
      "Classical Topic and Themes: War Scene",
      "Classical Topic and Themes: Architectural Study",
      "Classical Topic and Themes: City Scenery",
      "Classical Topic and Themes: Still Life",
      "Classical Topic and Themes: Industrial Life",
      "Classical Topic and Themes: Modernism Daily Life",
      "Classical Topic and Themes: Science Fiction",
      "Classical Topic and Themes: Abstract",
      "Texture: Primordial or Amoeba Formations",
      "Texture: Isolation or Psychological Trauma",
      "Political: Rancour",
      "Political: Sardonic",
      "Political: Bourgeois",
      "Political: Anti-Bourgeois",
      "Political: Pro Capitalist",
      "Political: Anti-Capitalist",
      "Political: Pro Communist",
      "Political: Anti-Communist",
      "Political: Fascist",
      "Political: Anti-Fascist",
      "Political: Sentimental",
      "Political: Avant-Garde",
      "Affections of Art or Topic: Sensual",
      "Affections of Art or Topic: Sweet",
      "Affections of Art or Topic: Cute",
      "Affections of Art or Topic: Tender",
      "Affections of Art or Topic: Sentimental",
      "Affections of Art or Topic: Grim",
      "Affections of Art or Topic: Dark",
      "Affections of Art or Topic: Sinister",
      "Affections of Art or Topic: Malicious",
      "Affections of Art or Topic: Elegant",
      "Affections of Art or Topic: Erotic",
      "Affections of Art or Topic: Brave",
      "Affections of Art or Topic: Triumphant",
      "Affections of Art or Topic: Anguish",
      "Advertisement Channels: Last Decade",
      "Advertisement Channels: 20s",
      "Advertisement Channels: 10s",
      "Advertisement Channels: 90s",
      "Advertisement Channels: 80s",
      "Advertisement Channels: 70s",
      "Advertisement Channels: 60s",
      "Advertisement Channels: 50s",
      "Advertisement Channels: 40s",
      "Advertisement Channels: 30s",
      "Advertisement Channels: Romantic",
      "Advertisement Channels: Neoclassic",
      "Advertisement Channels: Classical Times",
    ],
  },
];
