export interface CategoryGroup {
  title: string;
  categories: string[];
}

export const categoryGroups: CategoryGroup[] = [
  {
    title: "Era-Style",
    categories: [
      "Pyramid Eras",
      "Egyptian",
      "Sumerian",
      "Mesopotamian",
      "Aztec",
      "Ancient Whodanian (China Ancient)",
      "Ancient Pagan African",
      "Ancient Pagan Black Australian",
      "Ancient Pagan Indian",
      "Easter Island",
      "Ancient Island Cultures",
      "Ancient Pagan Arabian",
      "Ancient Pagan Japan",
      "Temple Cultures",
      "Greece",
      "Roman",
      "Japan",
      "China",
      "India",
      "Church Cultures",
      "Byzantian",
      "Roman Medieval",
      "Gothic Medieval",
      "Slavic Medieval",
      "Northern Europe Medieval",
      "Arabian Medieval",
      "First Enlightenment",
      "Renaissance",
      "Mannerism",
      "Baroque",
      "Rococo",
      "Second Enlightenment",
      "Neoclassicism",
      "Romanticism",
      "Symbolism",
      "Decadentism",
      "Empire",
      "Beidermeier",
      "Academics",
      "Decorative",
      "Arte Povera",
      "Artisan Conceptual",
      "Decorative Conceptual",
      "Kitsch Conceptual",
      "Solipsist Conceptual",
      "Technical Marvel Conceptual",
      "Late Modern Expressionism",
      "Modernism and Postmodernism Underground",
      "Impressionism",
      "Expressionism",
      "Fauvism",
      "Pointillism",
      "Dadaism",
      "Surrealism",
      "Conceptualism",
      "Abstraction",
      "NeoGothic Advent",
      "Futurism",
      "Haute Baroque",
      "Haute Rococo",
      "Haute Neoclassicism",
      "Islamic Golden Age",
      "Horror",
      "Post Modernism Underground",
      "Haute Minimalism",
      "Haute Symbolism",
      "Haute Romanticism (Black Metal)",
      "Martial Industrial",
      "Haute Surrealism",
      "Arch Baroque",
      "Arch Rococo",
      "Arch Neoclassicism",
      "Arch Horror",
      "Afrofuturism",
      "ASCII Art",
      "Abstract Art",
      "Art Brut",
      "Abstract Expressionism",
      "Abstract Illusionism",
      "Academic Art",
      "Aestheticism",
      "Altermodern",
      "American Barbizon School",
      "American Impressionism",
      "American Realism",
      "American Scene Painting",
      "Analytical Art",
      "Antipodeans",
      "Arabesque",
      "Arbeitsrat für Kunst",
      "Art & Language",
      "Art Deco",
      "Art Informel",
      "Art Nouveau",
      "Art Photography",
      "Artificial Intelligence Art",
      "Arts and Crafts Movement",
      "Ashcan School",
      "Assemblage",
      "Australian Tonalism",
      "Les Automatistes",
      "Auto-destructive Art",
      "Avant-garde",
      "Barbizon School",
      "Bauhaus",
      "Berlin Secession",
      "Black Arts Movement",
      "Bengal School of Art",
      "Brutalism",
      "Classical Realism",
      "Cloisonnism",
      "COBRA",
      "Color Field",
      "Context Art",
      "Computer Art",
      "Concrete Art",
      "Conceptual Art",
      "Constructivism",
      "Crystal Cubism",
      "Cubo-Futurism",
      "Cubism",
      "Cynical Realism",
      "Dada",
      "Dansaekhwa",
      "Danube School",
      "Dau-al-Set",
      "De Stijl",
      "Deconstructivism",
      "Didacticism",
      "Digital Art",
      "Ecological Art",
      "Environmental Art",
      "Modern European Ink Painting",
      "Excessivism",
      "Exoticism",
      "Fantastic Realism",
      "Fauvism",
      "Feminist Art",
      "Figurative Art",
      "Figuration Libre",
      "Fine Art",
      "Folk Art",
      "Flemish Painting",
      "Fluxus",
      "Funk Art",
      "Geometric Abstract Art",
      "Glitch Art",
      "Graffiti/Street Art",
      "Gutai Group",
      "Gothic Art",
      "Happening",
      "Harlem Renaissance",
      "Heidelberg School",
      "Hudson River School",
      "Hurufiyya",
      "Hypermodernism",
      "Hyperrealism",
      "Illustrative",
      "Interactive Art",
      "Institutional Critique",
      "International Gothic",
      "International Typographic Style",
      "Japonisme",
      "Kinetic Art",
      "Kitsch Movement",
      "Land Art",
      "Les Nabis",
      "Letterism",
      "Light and Space",
      "Lowbrow",
      "Lyco Art",
      "Lyrical Abstraction",
      "Magic Realism",
      "Mail Art",
      "Mannerism",
      "Massurrealism",
      "Maximalism",
      "Metaphysical Painting",
      "Mingei",
      "Minimalism",
      "Modernism",
      "Modular Constructivism",
      "Naive Art",
      "Neo-Dada",
      "Neo-expressionism",
      "Neo-Fauvism",
      "Neo-figurative",
      "Neo-primitivism",
      "Neo-romanticism",
      "Net Art",
      "New Objectivity",
      "New Sculpture",
      "Northwest School",
      "Nuclear Art",
      "Objective Abstraction",
      "Op Art",
      "Orphism",
      "Patna School of Painting",
      "Photorealism",
      "Panfuturism",
      "Paris School",
      "Pixel Art",
      "Plasticien",
      "Plein Air",
      "Pop Art",
      "Post-impressionism",
      "Postminimalism",
      "Precisionism",
      "Primitivism",
      "Private Press",
      "Process Art",
      "Psychedelic Art",
      "Purism",
      "Rayonism",
      "Realism",
      "Regionalism",
      "Remodernism",
      "Retrofuturism",
      "Romanesque",
      "Samikshavad",
      "Serial Art",
      "Shin Hanga",
      "Shock Art",
      "Sōsaku Hanga",
      "Socialist Realism",
      "Sots Art",
      "Space Art",
      "Street Art",
      "Stuckism",
      "Sumatraism",
      "Superflat",
      "Suprematism",
      "Synchromism",
      "Synthetism",
      "Tachisme",
      "Temporary Art",
      "Toyism",
      "Transgressive Art",
      "Tonalism",
      "Ukiyo-e",
      "Underground Comix",
      "Vancouver School",
      "Vanitas",
      "Verdadism",
      "Video Art",
      "Visual Art",
      "Viennese Actionism",
      "Vorticism",
      "Steampunk",
      "Primitive",
      "21st Century Avant-Garde",
      "NeoClassic",
      "NeoPagan",
      "Fantasy",
      "Industrial Deco"
    ]
  },
  {
    title: "Medium",
    categories: [
      "Lesbian Kisses Rococo",
      "Lesbian Kisses Baroque",
      "Lesbian Kisses Mannerism",
      "Lesbian Kisses Renaissance",
      "Lesbian Kisses Medieval Gothic",
      "Lesbian Kisses Medieval Roman",
      "Lesbian Kisses Roman",
      "Lesbian Kisses Greek",
      "Lesbian Kisses Mesopotamian",
      "Lesbian Kisses Egyptian",
      "Lesbian Kisses Indian",
      "Lesbian Kisses Far Orient",
      "Islamic Lesbian Kisses",
      "African Lesbian Kisses",
      "Lesbian Kisses Mix",
      "Blonde on Brunette",
      "Blonde on Blonde",
      "Brunette on Brunette",
      "Redheads Succubi Kisses",
      "Purple Hair",
      "Bleu Hair",
      "Emo Lesbian Kisses",
      "Vampire Lesbian Kisses",
      "Angel Lesbian Kisses",
      "Shieldmaidens Lesbian Kisses",
      "Emo Page Lesbian Kisses",
      "Search Incomplete (sketches, paint documents, amateur designing)",
      "Search Semicomplete (talented ideas, thorough paint projects, advanced design)",
      "Search Majesty (academic, fully composed, impeccable design)",
      "Seazon: Winter",
      "Seazon: Spring",
      "Seazon: Summer",
      "Seazon: Autumn",
      "Craft Medium: Oil Painting",
      "Craft Medium: Acrylic Painting",
      "Craft Medium: Aquarell",
      "Craft Medium: Engraving",
      "Craft Medium: Lithography",
      "Craft Medium: Monochrome",
      "Craft Medium: Monocolor",
      "Craft Medium: Collage",
      "Craft Medium: Relief",
      "Craft Medium: Bass Relief",
      "Craft Medium: Crayon",
      "Craft Medium: Pastel",
      "Craft Medium: Sketch",
      "Craft Medium: Virtual 2D",
      "Craft Medium: Virtual 3D",
      "Craft Medium: AI",
      "Artistic Color: Kitsch",
      "Artistic Color: Classic Decorative",
      "Artistic Color: Academic Sublime Decorative",
      "Artistic Color: Impressionistic",
      "Artistic Color: Expressionistic",
      "Artistic Color: Abstract Idealist",
      "Artistic Color: High Kitsch",
      "Artistic Color: Pastiche of Styles",
      "Metal Covers: Metal",
      "Metal Covers: Oldschool",
      "Metal Covers: Satanic",
      "Metal Covers: Trve Nature",
      "Metal Covers: Trve Experimental (Classic Victorian)",
      "Metal Covers: Trve Modern (Modern Features)",
      "Concept: Minimal",
      "Concept: Solipsistic",
      "Concept: Abstract Defaitist",
      "Concept: Installation",
      "Concept: Performance",
      "Concept: Post Deco Formal",
      "Concept: Conceptual Decorative",
      "Concept: Conceptual Allegoric",
      "Concept: Conceptual Technology",
      "Concept: Steampunk Styled",
      "Color: Black and White",
      "Color: Sepia",
      "Color: Red",
      "Color: Bleu",
      "Color: Yellow",
      "Color: Purple",
      "Color: Green",
      "Color: Orange",
      "Color: Technicolor",
      "Color: Hand Colored",
      "Color: Digital Color",
      "Theme: Historical Landscape",
      "Theme: Bridge",
      "Theme: Building",
      "Theme: Village",
      "Theme: Meadows",
      "Theme: Forest",
      "Theme: Still Life",
      "Theme: Life",
      "Theme: Technology",
      "Theme: Steam Era",
      "Theme: Television and Radio Era",
      "Modern Time Scenery: Post WWII",
      "Modern Time Scenery: Hippie Era",
      "Modern Time Scenery: 70s",
      "Modern Time Scenery: Early Synthpop",
      "Modern Time Scenery: Early New Wave Scene",
      "Modern Time Scenery: 80s",
      "Modern Time Scenery: Early Metal Scene",
      "Modern Time Scenery: 90s",
      "Modern Time Scenery: Early Black Metal Scene",
      "Modern Time Scenery: Internet Era Matrix",
      "Style of Life Depicted: Gluttony",
      "Style of Life Depicted: Enormous Wealth",
      "Style of Life Depicted: Decadence",
      "Style of Life Depicted: Monarchy",
      "Style of Life Depicted: Religious Life",
      "Style of Life Depicted: Civil Life",
      "Style of Life Depicted: Narrow Mindedness",
      "Style of Life Depicted: Labour",
      "Style of Life Depicted: Poverty",
      "Style of Life Depicted: Malnutrition",
      "Style of Life Depicted: Death",
      "Style of Life Depicted: Technology",
      "Style of Life Depicted: Fantasy",
      "Classical Topic and Themes: Mythology",
      "Classical Topic and Themes: Allegory",
      "Classical Topic and Themes: Portraits",
      "Classical Topic and Themes: Full Figure",
      "Classical Topic and Themes: Group",
      "Classical Topic and Themes: Classic Nude",
      "Classical Topic and Themes: Group Scene Classic Nude",
      "Classical Topic and Themes: Landscape Mountains / Meadows",
      "Classical Topic and Themes: Fantastic Landscape",
      "Classical Topic and Themes: War Scene",
      "Classical Topic and Themes: Architectural Study",
      "Classical Topic and Themes: City Scenery",
      "Classical Topic and Themes: Still Life",
      "Classical Topic and Themes: Industrial Life",
      "Classical Topic and Themes: Modernism Daily Life",
      "Classical Topic and Themes: Science Fiction",
      "Classical Topic and Themes: Abstract",
      "Texture: Primordial or Amoeba Formations",
      "Texture: Isolation or Psychological Trauma",
      "Political: Rancour",
      "Political: Sardonic",
      "Political: Bourgeois",
      "Political: Anti-Bourgeois",
      "Political: Pro Capitalist",
      "Political: Anti-Capitalist",
      "Political: Pro Communist",
      "Political: Anti-Communist",
      "Political: Fascist",
      "Political: Anti-Fascist",
      "Political: Sentimental",
      "Political: Avant-Garde",
      "Affections of Art or Topic: Sensual",
      "Affections of Art or Topic: Sweet",
      "Affections of Art or Topic: Cute",
      "Affections of Art or Topic: Tender",
      "Affections of Art or Topic: Sentimental",
      "Affections of Art or Topic: Grim",
      "Affections of Art or Topic: Dark",
      "Affections of Art or Topic: Sinister",
      "Affections of Art or Topic: Malicious",
      "Affections of Art or Topic: Elegant",
      "Affections of Art or Topic: Erotic",
      "Affections of Art or Topic: Brave",
      "Affections of Art or Topic: Triumphant",
      "Affections of Art or Topic: Anguish",
      "Advertisement Channels: Last Decade",
      "Advertisement Channels: 20s",
      "Advertisement Channels: 10s",
      "Advertisement Channels: 90s",
      "Advertisement Channels: 80s",
      "Advertisement Channels: 70s",
      "Advertisement Channels: 60s",
      "Advertisement Channels: 50s",
      "Advertisement Channels: 40s",
      "Advertisement Channels: 30s",
      "Advertisement Channels: Romantic",
      "Advertisement Channels: Neoclassic",
      "Advertisement Channels: Classical Times",
    ],
  },
  {
    title: "Army",
    categories: [
      "VAMPIRE LEGIONS",
      "Vhempyhren Gestapo",
      "Vhempeyhren General Command Post",
      "Vampire Gestapo",
      "Vampire Gestapo General Command Post",
      "Blood Tyrant General Command Post",
      "Blood Tyrant Legions",
      "âmes sanglantes & the wampyric specter General Command Post",
      "âmes sanglantes & the wampyric specter Legions",
      "Vlad Tepes General Command Post",
      "Vlad Tepes Legions",
      "Drowning The Light General Command Post",
      "Drowning The Light Legions",
      "Mutiilation General Command Post",
      "Mutiilation Legions",
      "Aâkon këëtreh General Command Post",
      "Aâkon këëtreh Legions",
      "Unholy Vampyric Slaughter Sect General Command Post",
      "Unholy Vampyric Slaughter Sect Legions",
      "Vorlok General Command Post",
      "Vorlok Legions",
      "Vermyapre Kommando General Command Post",
      "Vermyapre Kommando Legions",
      "Chatiment General Command Post",
      "Chatiment Legions",
      "Shadow Vampire Secret Service",
      "Vampire Legions",
      "Vampire Command Post",
      "TWO MILLION VEMPIRE CRUSADORS GENERAL COMMAND POST",
      "TWO MILLION VEMPIRE CRUSADORS LEGIONS GALORE",
      "ELLEXEM",
      "LAtex Matrix Police forces",
      "WHITE LATEX virtual mehre technology portal protection",
      "PURPLE LATEX defending aristocratic people",
      "RED LATEX OR INSIGNA vampire and vampiric protection",
      "BLEU LATEX OR INSIGNA elvish",
      "Angh Angel Legions",
      "Shadow Legions",
      "Cultus Sanguine General Command Post",
      "Cultus Sanguine Legions",
      "PAGAN LEGIONS",
      "Roman Legions",
      "Blackshields (Spain and France pagans)",
      "Scandinavian Vikings",
      "Spartan Legions",
      "Hellenic Legions",
      "Ancient Indian Legions",
      "Ancient China Legions",
      "Gogo Yubari Elite Squadrons",
      "Ancient Mongol Legions",
      "Ancient Arabian Legions",
      "MEDIEVAL LEGIONS",
      "Teutonic KNights",
      "Knights Templars",
      "Maltese Knights",
      "Flemish Knights",
      "Brabant Knights",
      "Spanish Knights",
      "Portugese Knights",
      "Ottoman Legions",
      "Islamic Legions",
      "MARTIAL INDUSTRIAL",
      "MARTIAL INDUSTRIAL GENERAL COMMAND POST",
      "MARTIAL INDUSTRIAL LEGIONS",
      "Tsidmz General Command Post",
      "Tsidmz Emperial Cohorts",
      "Horologium General Command Post",
      "Horologium Emperial Cohorts",
      "Nevod General Command Post",
      "Nevod Emperial Cohorts",
      "Triarii General Command Post",
      "Triarii Emperial Cohorts",
      "Legionarii General Command Post",
      "Legionarii Emperial Cohorts",
      "Arditi General Command Post",
      "Arditi Emperial Cohorts",
      "Von Thronstahl General Command Post",
      "Von Thronstahl Emperial Legions",
      "March Of Heroes General Command Post",
      "March Of Heroes Emperial Legions",
      "MARTIAL FOLK",
      "Martial Folk Generals",
      "In Gowan Ring General Command Post",
      "Blood Axis General Command Post",
      "Blood Axis Emperial Legions",
      "Triore General Command Post",
      "Leger Des Heils General Command Post",
      "Leger Des Heils Emperial Legions",
      "BLACK METAL",
      "Black Metal General Command Post",
      "Black Metal Legions",
      "Sammath General Command Post",
      "Sammath Legions",
      "Ad Hominem General Command Post",
      "Ad Hominem Legions",
      "Ad Hominem Hate Squads",
      "Black Plague General Command Post",
      "Black Plague Legions",
      "Fangorn General Command Post",
      "Fangorn Legions",
      "Dark Funeral General Command Post",
      "Dark Funeral Legions",
      "Samael General Command Post",
      "Samael Legions",
      "Satyricon General Command Post",
      "Satyricon Legions",
      "Gorgoroth General Command Post",
      "Gorgoroth Legions",
      "Mayhem General Command Post",
      "Mayhem Legions",
      "Behemoth General Command Post",
      "Behemoth Legions",
      "Behemoth Special Elvish Warlords Committee",
      "NKVD Secret Service",
      "NKVD General Command Post",
      "NKVD Secret Legion Of Military Police",
      "DOOM",
      "My Dying Bride General Command Post",
      "My Dying Bride Legions",
      "Murkrat General Command Post",
      "Murkrat Legions",
      "Anathema General Command Post",
      "Anathema Legions",
      "Paradise Lost General Command Post",
      "Paradise Lost Legions",
      "TRASH",
      "Deicide General Command Post",
      "Deicide Legions",
      "Slayer General Command Post",
      "Slayer Legions",
      "Megadeth General Command Post",
      "Megadeth Legions",
      "Metallica General Command Post",
      "Punk",
      "The Exploited General Command Post",
      "The Exploited Legions",
      "The Clash General Command Post",
      "The Clash Legions",
      "The Stranglers General Command Post",
      "The Stranglers Legions",
      "Grindcore",
      "Slipknot General Command Post",
      "Slipknot mosh Squads.",
      "Grunge",
      "Nirvana General Command Post",
      "Nirvana Legions",
      "Rock",
      "69 Eyes General Command Post",
      "69 Eyes Legions",
      "Muse General Command Post",
      "Muse Legions",
      "ARMY II",
      "THE FIRST ARMY",
      "Army of Generals",
      "THE SECOND ARMY",
      "Black Metal Legion general Command Post",
      "Metal Army (Trashing limbs)",
      "Metal Army (heavy prowess)",
      "Rock Army",
      "Stone Army",
      "Muse Uprisal Army",
      "Bleu Army",
      "Black Panther Movement",
      "THE THIRD ARMY",
      "soldier / activist / support",
      "Corporal",
      "Sergeant",
      "Captain",
      "Lieutenant",
      "General",
      "THE FOURTH ARMY",
      "Civil control Army",
      "submit footage and information on ...",
      "war, wars, battles, tactics",
      "war crime, murder, riot, running amok, rampage with vehicle, tank/bulldozer/other",
      "artistic provocation",
      "build a profile for each of your weapons",
      "Weapons",
      "Arsenals",
      "Swords",
      "Daggers",
      "Guns",
      "Pistols",
      "Machine guns",
      "Heavy artillery",
      "Cannons",
      "Choppers",
      "War planes",
      "Jet fighters",
      "Smaller war ships",
      "Larger war ships"
    ]
  },
  {
    title: "Empresses",
    categories: [
      "Empress of the Oceans",
      "Empress of the Forests",
      "Empress of the Deserts",
      "Empress of the Rivers",
      "Empress of the Lakes",
      "Empress of Fauna",
      "Empress of Flora",
      "Empress of Human Rights",
      "Empress of Defence",
      "Empress of Agreculture",
      "Empress of the Dead",
      "Empress of science",
      "Empress of the Atlantic Ocean",
      "Empress of the Pacific Ocean",
      "Empress of the Middeterranian Sea",
      "Empress of the Indian Ocean",
      "Empress of the Nile",
      "Empress of the Amazone",
      "Empress of the Ellendeh river",
      "Empress of the Theems",
      "Empress of the Taag",
      "Empress of the Rhine",
      "Empress of Amneherhea",
      "Empress of Canada",
      "Empress of Central America",
      "Empress of South America",
      "Empress of europe Aerewvea",
      "Empress of Arabia",
      "Empress of Mesopotamia",
      "Empress of Russia",
      "Empress of India",
      "Empress of China Whodana",
      "Empress of Japan",
      "Empress of Australia and New Zealand",
      "Empress of Africa",
      "Empress of greenland",
      "Empress of Antarctica",
      "Empress of the United Orient Nations",
      "Empress of Jerusalem",
      "Empress of AnaehtheanA Fantasy City HOME",
      "Empress of Brussels And the Capital of (HellexxxelleH)",
      "Empress of Washington And the New Capital of AmnheherheA",
      "Empress of Moscow And the New Capital of Russia",
      "Empress of Rome And the New CApital of Antiquity",
      "Empress of Beijing And the New CApital of Whodanha",
      "Empress of New Delhi And the nEw CApital of India",
      "Empress of Sidney And the New Capital of Australia",
      "Empress of Cairo And the New Capital of Ancient Egypt",
      "Empress of Mekka And the New Capital Of Arabia",
      "Empress of South America or the New Capital of West AmnheherheA",
      "Empress of Congo District of the Capital of Africa"
    ]
  },
  {
    title: "Banners",
    categories: [
      "Idealistic",
      "Nihilistic",
      "Utopic",
      "Distopic",
      "Arcadian",
      "Moral relativism",
      "Moral highground",
      "Sexism",
      "Antisexism",
      "Left wing",
      "Right wing",
      "The Index",
      "Propagandh",
      "Propaganda",
      "Commercial",
      "Classic Commercial",
      "Artisan Commercial",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "Flyer",
      "Poster",
      "Sketch Book Paper Size",
      "Steinbach",
      "Delville maximum",
      "Etherith maximum",
      "Metaetherith maximum",
      "Vempiric sizes",
      "Banner",
      "Flag",
      "Prophetic Recitation",
      "Intellectual Recitation",
      "Meme",
      "Literary poster",
      "Ideological poster",
      "Ironic content",
      "Historical reference or treatize",
      "Conspiracy reference or treatise",
      "Arch Symbolist Banners",
      "Illustrated Journals",
      "Online Illustrated Journals",
      "Art Magazines",
      "Online Art Magazines",
      "Music magazines",
      "Online Music Magazines",
      "Gossip and Tabloid",
      "Online Gossip and tabloid",
      "Newspapers",
      "Online Newspapers",
      "Luciferium Wargraphics Banners",
      "Emperor of the Logo's Depravarts Alemsahim Banners",
      "Metallum Banners",
      "Moonring Design",
      "King of the Logo's Spjadel Banners",
      "Banners",
      "Death Metal Banners",
      "Trash Metal Banners",
      "Punk Banners",
      "Rock Banners",
      "Gatherings",
      "Venues",
      "Festivals",
      "Events",
      "Pubs",
      "Bars",
      "Hotels",
      "Restaurants",
      "Online Ecological Movements",
      "Online Ecological Information",
      "Online Myths",
      "Online Faerytales",
      "Online Novels",
      "Online communities",
      "Online media channels"
    ]
  },
  {
    title: "Heaven",
    categories: [
      "Astronauts",
      "Pilots",
      "Engineers",
      "Ground Technicians",
      "Space Agencies",
      "Worldwide",
      "Russia",
      "European",
      "North America",
      "South America",
      "Africa",
      "Arabian",
      "Indian",
      "China",
      "Japan",
      "Australia",
      "Launch and Crafts",
      "Heaven Ships and Vessels Craft Ateliers",
      "Modernist Launching Platform",
      "Eiffel Tower Launching Platform (with electromagnetic rail initial propulsion, and four second stage advanced combustion.)",
      "Earth Inventory and Virtual World Construction Satellites",
      "Manned",
      "Unmanned",
      "Observation",
      "Heaven Telescopes, Inner Solar System Traffic, Outer Solar System Traffic",
      "Transportation",
      "Heaven Ships",
      "Vessels for Distance",
      "Residences",
      "Cities, Palaces, Residences, Terraforming Plans, Planet Trajectory Course Adjustment Plans, Mining, Garden and Biosphere Construction, Garden Biosphere Mantle Project",
      "For Moon",
      "Mars",
      "Europa",
      "The Spacecraft Mission",
      "Inner Solar System",
      "Outer Solar System",
      "Exo Solar System",
      "Exoplanet",
      "Venus",
      "Aeylyeaelle Moon And Mars Secondary Stages, Terraforming, Classical Cities, Main Transit Infrastructure and Development",
      "Entrepreneur Space Projects",
      "Elon Musk",
      "Jeff Bezos",
      "Richard Branson"
    ]
  },
  {
    title: "Location",
    categories: [
      "City States",
      "AnaehtheanA",
      "Hellexxxelleh",
      "Hassallath",
      "Amnherhrea Capitol",
      "Asshana Capitol",
      "aerawvhea Capitol",
      "Third Belt of Hell",
      "Ouwhrlean Belt",
      "Continent",
      "Aerhevwhea",
      "Amnherhrhea NORTH",
      "Amnherhrea WEST",
      "Aeshea",
      "Ouwhsheanea",
      "Aerehephvhrea",
      "select country",
      "Aerhevhea Europe",
      "Albania",
      "Andorra",
      "Armenia",
      "Austria",
      "Azerbaijan",
      "Belarus",
      "Belgium",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Cyprus",
      "Czechia",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hungary",
      "Iceland",
      "Ireland",
      "Italy",
      "Kazakhstan",
      "Kosovo",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Moldova",
      "Monaco",
      "Montenegro",
      "Netherlands",
      "North Macedonia",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Russia",
      "San Marino",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
      "Turkey",
      "Ukraine",
      "United Kingdom (UK)",
      "Vatican City (Holy See)",
      "Amnherhea NORTH",
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
      "Ontario",
      "Quebec",
      "Nova Scotia",
      "New Brunswick",
      "Manitoba",
      "British Columbia",
      "Prince Edward Island",
      "Saskatchewan",
      "Alberta",
      "Newfoundland and Labrador",
      "Amnherhea WEST",
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela",
      "AEHSHEA",
      "India",
      "China",
      "Indonesia",
      "Pakistan",
      "Bangladesh",
      "Japan",
      "Philippines",
      "Vietnam",
      "Iran",
      "Turkey",
      "Thailand",
      "Myanmar",
      "South Korea",
      "Iraq",
      "Afghanistan",
      "Saudi Arabia",
      "Uzbekistan",
      "Yemen",
      "Malaysia",
      "Nepal",
      "North Korea",
      "Syria",
      "Sri Lanka",
      "Kazakhstan",
      "Cambodia",
      "Jordan",
      "Azerbaijan",
      "Tajikistan",
      "United Arab Emirates",
      "Israel",
      "Laos",
      "Kyrgyzstan",
      "Turkmenistan",
      "Singapore",
      "State of Palestine",
      "Lebanon",
      "Oman",
      "Kuwait",
      "Georgia",
      "Mongolia",
      "Armenia",
      "Qatar",
      "Bahrain",
      "Timor-Leste",
      "Cyprus",
      "Bhutan",
      "Maldives",
      "Brunei"
    ]
  },
  {
    title: "Library",
    categories: [
      "xVolume",
      "book exerpt",
      "book summary",
      "book main page",
      "essay",
      "quotation",
      "Famous last words",
      "Nature",
      "Art Book",
      "Photography Book",
      "Artisan Craftwork (wood or locks)",
      "Type",
      "Fiction",
      "Non-Fiction",
      "Fantasy",
      "Mythology",
      "Religion",
      "Occult",
      "Children",
      "Adult",
      "Technique",
      "Poetry",
      "Free verse",
      "Proze poetry",
      "Proze",
      "Biography",
      "Autobiography",
      "Journalism/reporting",
      "Historic",
      "Semi historic",
      "Experimental",
      "Interview",
      "Style",
      "Satire",
      "Tragedy",
      "Pharce",
      "Comedy",
      "Phrasis",
      "Mythology",
      "Philosophy",
      "Aphorisms",
      "Lyrics",
      "Classical literature",
      "Romantic literature",
      "Occult",
      "Avant garde literature",
      "Sociology",
      "Early psychology",
      "Intent",
      "Literature",
      "Play",
      "Screenplay",
      "Themes",
      "Opression",
      "Christianity",
      "Anti-Christianity",
      "Fascism",
      "Communism",
      "Left leaning topics",
      "Right leaning topics",
      "Left leaning argumentation",
      "Right leaning argumentation",
      "Hinduism",
      "Race",
      "History",
      "Modernism",
      "Anti-modernism",
      "Aliens"
    ]
  },
  {
    title: "Music",
    categories: [
      "Vinyl",
      "Casette",
      "CD",
      "DVD",
      "Music clip",
      "Footage clip",

      "Official Video",
      "Unofficial Video",
      "Studio",
      "Live",
      "Daycore Slow Ambient",
      "Nightcore",
      "Extended",
      "Snippet",
      "Song",
      "EP",
      "Full Length",
      "Three CD",
      "One Day Long Opera",
      "One Week Long Opera",
      "Three Week Long Opera",
      "Over Three Weeks",
      "Titanium Opera",
      "Vampiric Christian Black Metal",
      "Roman Catholic Black Metal",
      "Evangelical Black Metal",
      "Christian Black Metal",
      "Islamic Black Metal",
      "Renaissance Christian Rose Croix Pagan Black Metal",
      "Uniting Islamism with Subjectivity",
      "Uniting Islam with Christianity",
      "Uniting Christianity with Ancient Egypt",
      "Uniting Islam with Paganism",
      "Supreme Black Metal",
      "Holy Corona Black Metal",
      "Universal Symphonic Odes",
      "Marsia Black Metal",
      "Luna Black Metal",
      "Lilithstar Black Metal",
      "Vampiric Communist Black Metal",
      "Spiritual Vampiric Dream Black Metal",
      "Light Vampire Elvish Black Metal",
      "Techno Vampire Black Metal",
      "EBM Black Metal Vampiric Dance & Baroque",
      "Spiritual Martial Industrial",
      "Childish Martial Industrial",
      "Imagery of a Daylight Sky Synth",
      "Night Black Metal",
      "Ghost Black Metal",
      "Fascist Vampiric Dance",
      "Fascist Vampiric Trance",
      "Female Fascist Vampiric Pop",
      "Anti Civil Provocative Black Metal",
      "Schizophrenic Black Metal",
      "Strigoi Black Metal",
      "Elitist Black Metal",
      "VhempeyhreN Black Metal",
      "Wampyr Gestapo Black Metal",
      "Gothic Vampiric Metal",
      "Aryan Black Metal",
      "Werewolf Commando's Black Metal",
      "Order of the Deaths Head Black Metal",
      "Principii Black Metal",
      "Dungeon Synth",
      "Martial Industrial",
      "Werewolf Martial Industrial",
      "Vampiric Tyrant Martial Industrial",
      "Christian Martial Industrial",
      "Satanic Martial Industrial",
      "NSBM",
      "Communist Black Metal",
      "Black Metal",
      "DSBM",
      "Sexist Black Metal",
      "Parthenophilic Black Metal",
      "Political Black Metal",
      "Templar Order Black Metal",
      "Illegal Black Metal",
      "Death Metal",
      "Death Grind",
      "Trash Metal",
      "Punk",
      "Emo Music",
      "Gothic Synthwave",
      "Fascwave",
      "Industrial",
      "EBM",
      "Trance",
      "Ambient",
      "Techno",
      "House",
      "Hardcore",
      "Industrial Hardcore",
      "Bonzai",
      "Terror",
      "Melodic",
      "Symphonic",
      "Medieval",
      "Baroque",
      "Symbolist",
      "Etnic Music",
      "World Music",
      "Melancholic",
      "Silent",
      "Timid",
      "Violent",
      "Ultraviolent",
      "Blast Beats",
      "Venomous Rage",
      "Lightning Techno",
      "Thunder Techno",
      "Nuclear Techno"
    ]
  },
  {
    title: "Empire",
    categories: [
      "Photography", "Silent Film", "Motion Picture", "Documentary Film", "Art Film",
      "Oil Painting", "Painting", "Watercolor", "Mural", "Drawing", "Engraving", "Color Print", "Posters", "Wallpaper", "Mosaic", "Tapestry", "Vase Painting",
      "Sculpture", "Small Sculpture", "Bass Relief", "Column", "Cariatide Pedestal",
      "Frame", "Stained Glass", "Ceramics", "Pottery",
      "Maquette Wood", "Maquette Carton Board Paper",
      "Jewelry", "Rings", "Necklaces", "Piercings",
      "Body Art", "Painted", "Tattooed", "Pierced",
      "Money", "Coins", "Paper Money", "Old Stocks",
      "Medals", "Honorary Art",
      "Tableware", "Silverware",
      "Boxes", "Coffins",
      "Chess Games", "Other Games",
      "Chandelier", "Candelabra", "Candlesticks", "Wall Sconce", "Lamps",
      "Furniture", "Tables", "Chairs", "Closets", "Mirrors", "Clocks", "Television Sets", "Music Players", "Electronics", "Heating", "Cookers",
      "Bookcase", "Cabinet", "Fire/Stove Surround", "Beds",
      "Classic, Authentic or Luxurious Bathrooms", "Sinks", "Baths", "Showers", "Toilets",
      "Other Small Antique Objects", "Other Large Antique Objects",
      "Instruments", "Lyre", "Guitar", "Piano", "Horn", "Flute", "Organ", "Oboe", "Clarinet", "Cello", "Viola", "Harpsichord", "Drums and Other Percussion",
      "Submit Material", "Ceramic", "Woodenware", "Aluminium", "Brass", "Bronze", "Glass", "Porcelain", "Gold", "Copper", "Silver", "Wood", "Stone", "Marble", "Ivory",
      "Fabric if Applicable", "Velvet", "Lace", "Silk", "Cotton",
      "Architecture", "Architecture Was Intended For", "Architecture Was Used For", "Architecture Presently In Use For",
      "Building", "Palace", "Castle", "Temple", "Temple Complex", "Church", "Cathedral", "Chapel", "Mosque", "Market Square", "City Hall", "Opera House", "Concert Hall", "Movie Theatre", "Museum", "Arena",
      "Hospital", "Psychiatry",
      "Suburban House", "House", "Mansion", "Farmhouse",
      "Architectural Scenery", "Staircases", "Salons", "Dining Rooms", "Ballrooms", "Dressing Rooms", "Kitchens",
      "Decorative Metal Works", "Bridges", "Decorative Bridge", "Functional Bridge", "Suspension Bridge",
      "Well", "Street", "Avenue", "Boulevard", "Lane",
      "Artisan or Early Industrial Building", "Village", "City",
      "State", "Ruin", "Vacant", "For Rent", "For Sale", "On Fire", "Within Natural Scenery",
      "Nature", "Small Natural Scenes", "Gardens", "Small Rivers, Wells or Pools", "Rivers and Lakes", "Waterfalls", "Forests", "Tree", "Plant", "Flower",
      "Mountain", "Mountainside", "Valley", "Cliff",
      "Region", "Province", "Nation", "Continent", "Planet",
      "Wild Animals",
      "Vehicles", "Carriages and Motorized Vehicles", "Trains", "Elevators",
      "Artisan Clothing Ateliers", "Artisan Construction Ateliers", "Artisan Stores", "Artisan Farms",
      "Artistic Farm (1-10 Pigs, 1-10 Horses, Under 50 Chickens, Under 10 Cows)",
      "Professional Artistic Farm (10-100 Pigs, 10-100 Horses, 50-500 Chickens, 10-50 Cows)",
      "Industrial Farm (Over 100 Pigs, Over 100 Horses, Over 500 Chickens, Over 50 Cows)",
      "Artisan Foods", "Bread", "Cheese", "Vegetable Garden", "Poultry", "Meats", "Soaps", "Beauty Products", "Cosmetics", "Paint",
      "Tool",
      "Color If Applicable", "Black", "White", "Sepia", "Purple", "Red", "Orange", "Yellow", "Green", "Blue", "Pink",
      "Inventions", "Romantic Marvels", "Records of Utterly Chilling Extreme Human Challenges or Events",
      "X Compose for the Future Now at Last Without Any Unintended Cynical Undertone",
      "Beautiful Billboards",
      "Market",
      "XProfile Involves", "Fantastic Nature Composures", "Solely Nature (No Humans or Cultural Objects to Be Seen)",
      "Nature (With Human or Cultural Objects Within Picture)",
      "Artificial Natural Scene (Neoclassical or Other Garden Scaping)",
      "Fantastic and Grotesque Cultural Composures",
      "Extinct Species", "Recently Extinct Species (Caused by Man)", "Soon to Be Extinct Species",
      "Disasters", "Environmental Disasters", "Grand Dismemberment of Environmental or Cultural Value",
      "XSubmit", "Social Interaction or Cultural or Political Cons and Schemes",
      "Hacking Methods", "Spamming Methods", "Con Arts", "Symbolist Theories", "Architectural Theory and Equations",
      "Technologic Theory and Equations and Plans", "Program Languages",
      "Conceptual, Cartoons, Comics, World Records, Political Clumsiness, Digital Fantasy, Old School, Trash, Modernist Entertainment Literature",
      "XSubmit to the Empire",
      "Scandals", "Commemorable Crap", "Forbidden Toxic Past, Present or Soon Released Toxic Products",
      "Beautiful or Epic Administration", "File Only Old Documents or Those Paperwork Items of Truly Epic Proportions",
      "Anatomic Drawings and Studies", "Diseases",
      "Epic Gore Treatment of Human Beings", "Torture",
      "Psychiatric and Other Treatments", "Medication and Side Effects (Anti-Psychiatry That Is Not Lobbied Entries Only)",
      "Logos", "Type Fonts", "Frames", "Backgrounds", "Layout Props"
    ]
  },

];
